# Generated by Django 6.0.3 on 2026-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_learned',
            field=models.BooleanField(default=False, verbose_name='Is learned'),
        ),
    ]
