# Generated by Django 6.0.3 on 2026-04-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_word_is_learned'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название набора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Набор слов',
                'verbose_name_plural': 'Наборы слов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='word',
            name='word_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='cards.wordset', verbose_name='Набор'),
        ),
    ]
